' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/23/19 by Alan Hurley
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Assem3.2", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, True, 1, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02228832625857628605, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.02786040782322036016, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.02786040782322036016, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03900457095250850492, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01114416312928814302, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02228832625857628605, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05014873408179664621, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03343248938786443081, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.03900457095250850492, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02228832625857628605, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0.03900457095250850492, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.02228832625857628605, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01114416312928814302, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4334218791251487346, -0.09143669053583636241, 0.0706969036465636691

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Dim sViewData As Object
Set sViewData = Part.ModelViewManager.CreateSectionViewData()
Set sViewData.FirstPlane = Nothing
sViewData.FirstReverseDirection = False
sViewData.FirstOffset = 0
sViewData.FirstRotationX = 0
sViewData.FirstRotationY = 0
sViewData.FirstColor = 16711680
sViewData.ShowSectionCap = False
sViewData.KeepCapColor = False
sViewData.GraphicsOnlySection = False
sViewData.ZonalSection = True
sViewData.SectionedZones = 2
sViewData.SelectiveSection = False
sViewData.ExcludeSelectedItems = True
sViewData.TransparentSection = False
sViewData.SectionTransparentItemsTransparent = True
sViewData.TransparencyValue = 0.9
boolstatus = Part.ModelViewManager.CreateSectionView(sViewData)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05014873408179664621, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01754612918228345975, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0204704840459973697, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02631919377342518615, -0.07243706034037293573, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, -0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, -0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03509225836456691949, -0.1114416312928814407, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, -0.0612928972110847875, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02631919377342518615, -0.06686497877572886162, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01754612918228345975, -0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, -0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02631919377342518615, 0.06686497877572886162, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.05014873408179664621, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01754612918228345975, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0204704840459973697, 0.05014873408179664621, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01754612918228345975, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.0612928972110847875, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.05014873408179664621, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.0445766525171525721, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, -0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05572081564644072033, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06686497877572886162, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0204704840459973697, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04386532295570864937, -0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01754612918228345975, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04094096809199473941, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01462177431856954979, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0204704840459973697, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02631919377342518615, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0204704840459973697, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, 0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03216790350085300954, 0.0612928972110847875, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01754612918228345975, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0204704840459973697, 0.02786040782322036016, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04094096809199473941, 0.05014873408179664621, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04094096809199473941, 0.06686497877572886162, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02631919377342518615, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02339483890971127966, 0.03343248938786443081, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008773064591141729873, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01169741945485563983, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0204704840459973697, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01754612918228345975, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01462177431856954979, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03509225836456691949, -0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005848709727427819915, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03900457095250850492, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.0167162446939322154, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01169741945485563983, -0.02228832625857628605, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, -0.01114416312928814302, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, -0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005848709727427819915, 0, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002924354863713909958, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.005572081564644071512, -0.4915272386118090253, -0.08003653331679316807, 0.0203990638927962209

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(-0.4001801682482550859, 0.09422851016984168382, 0.05145375927997974941, 0.1591446398917886473, -0.09285866846258931939, 0.982878553680498257, 0.001004750956267785444, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByRay(-0.3645233084598658024, -0.1649527595399646884, 0, 0.1591446398917886473, -0.09285866846258931939, 0.982878553680498257, 0.001004750956267785444, 2, False, 0, 0)
boolstatus = Part.Extension.SelectByRay(-0.36482229986391701, -0.1649335053579150667, 0, 0.1591446398917886473, -0.09285866846258931939, 0.982878553680498257, 0.001004750956267785444, 2, False, 0, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, True, 1, Nothing, 0)
Set sViewData = Part.ModelViewManager.CreateSectionViewData()
Set sViewData.FirstPlane = Nothing
sViewData.FirstReverseDirection = True
sViewData.FirstOffset = 0
sViewData.FirstRotationX = 0
sViewData.FirstRotationY = 0
sViewData.FirstColor = 16711680
sViewData.ShowSectionCap = False
sViewData.KeepCapColor = False
sViewData.GraphicsOnlySection = False
sViewData.ZonalSection = False
sViewData.SectionedZones = 0
sViewData.SelectiveSection = False
sViewData.ExcludeSelectedItems = True
sViewData.TransparentSection = False
sViewData.SectionTransparentItemsTransparent = True
sViewData.TransparencyValue = 0.9
boolstatus = Part.ModelViewManager.CreateSectionView(sViewData)
Part.ClearSelection2 True
swApp.ExitApp
End Sub
